---
abstract: "A Python-style \"command line interpreter\" for Perl"
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Shell
name: Perl-Shell
no_index:
  directory:
    - inc
    - t
requires:
  Lexical::Persistence: 1.01
  PPI: 1.205
  Params::Util: 1.00
  Term::ReadLine: 0
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Perl-Shell
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Shell
version: 0.03
